<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\AdvertController2' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/AdvertController2.php';

return $this->services['App\\Controller\\AdvertController2'] = new \App\Controller\AdvertController2();
