<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'antares_accessible.constraints_validation.validator' shared service.

include_once $this->targetDirs[3].'/vendor/antares/accessible-bundle/Service/NullService.php';

return $this->services['antares_accessible.constraints_validation.validator'] = new \Antares\Bundle\AccessibleBundle\Service\NullService();
