<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMojm3i8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMojm3i8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMojm3i8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMojm3i8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMojm3i8\srcDevDebugProjectContainer([
    'container.build_hash' => 'Mojm3i8',
    'container.build_id' => '8a2a0ece',
    'container.build_time' => 1561657505,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMojm3i8');
